"""Initial data

Revision ID: a40f748cad06
Revises: 
Create Date: 2017-11-29 09:07:38.161986
"""

import sqlalchemy as sa
from alembic import op

from sqlalchemy.sql.ddl import CreateSchema, DropSchema

# revision identifiers, used by Alembic.
revision = 'a40f748cad06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSchema('plugin_checkin_webhook'))
    # ### commands auto generated by Alembic  ###
    op.create_table(
        'checkin_webhook_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('webhookurl', sa.String(), nullable=False),
        sa.Column('ticket_template_id', sa.Integer(), nullable=False),
        sa.Column('send_json', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['event_id'], [u'events.events.id'], name=op.f('fk_checkin_webhook_settings_event_id_events')),
        sa.ForeignKeyConstraint(
            ['ticket_template_id'], [u'indico.designer_templates.id'],
            name=op.f('fk_checkin_webhook_settings_ticket_template_id_designer_templates')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin_webhook_settings')),
        schema='plugin_checkin_webhook')
    op.create_index(
        op.f('ix_checkin_webhook_settings_event_id'),
        'checkin_webhook_settings', ['event_id'],
        unique=False,
        schema='plugin_checkin_webhook')
    op.create_index(
        op.f('ix_checkin_webhook_settings_ticket_template_id'),
        'checkin_webhook_settings', ['ticket_template_id'],
        unique=False,
        schema='plugin_checkin_webhook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(
        op.f('ix_checkin_webhook_settings_ticket_template_id'),
        table_name='checkin_webhook_settings',
        schema='plugin_checkin_webhook')
    op.drop_index(
        op.f('ix_checkin_webhook_settings_event_id'),
        table_name='checkin_webhook_settings',
        schema='plugin_checkin_webhook')
    op.drop_table('checkin_webhook_settings', schema='plugin_checkin_webhook')
    # ### end Alembic commands ###
    op.execute(DropSchema('plugin_checkin_webhook'))
